name: Dart CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    paths:
      - setup.sh
      - action.yml
jobs:
  lint_shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ludeeus/action-shellcheck@master
  test_channel:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
        channel: [stable, beta, master]
    steps:
    - uses: actions/checkout@v3
    - id: flutter-action
      uses: ./
      with:
        channel: ${{ matrix.channel }}
    - name: Echo outputs
      run: |
        echo CACHE-PATH=${{ steps.flutter-action.outputs.CACHE-PATH }}
        echo CACHE-KEY=${{ steps.flutter-action.outputs.CACHE-KEY }}
        echo CHANNEL=${{ steps.flutter-action.outputs.CHANNEL }}
        echo VERSION=${{ steps.flutter-action.outputs.VERSION }}
        echo ARCHITECTURE=${{ steps.flutter-action.outputs.ARCHITECTURE }}
      shell: bash
    - run: dart --version
      shell: bash
    - run: flutter --version
      shell: bash
  test_cache:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v3
    - uses: ./
      with:
        channel: stable
        cache: true
    - run: dart --version
      shell: bash
    - run: flutter --version
      shell: bash
  test_print_output:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        architecture: x64
    - run: flutter pub get
    - run: flutter test
    - run: flutter build ios --release --no-codesign


  
  
  
  
  
  
  
  
    
